---
abstract: 'Automatically convert POD to a README for Dist::Zilla'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100991'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ReadmeFromPod
recommends: {}
requires:
  Dist::Zilla: 1.007
  File::Temp: 0
  IO::Handle: 0
  Pod::Readme: 0.09
resources:
  repository: http://github.com/avar/dist-zilla-plugin-readmefrompod
version: 0.07
