---
abstract: 'Automatically convert POD to a README for Dist::Zilla'
author:
  - 'Fayland Lam <fayland@gmail.com>'
  - 'Ævar Arnfjörð Bjarmason <avar@cpan.org>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ReadmeFromPod
no_index:
  directory:
    - t
requires:
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::InstallTool: 5
  Moose: 0
  Moose::Autobox: 0
  Pod::Simple: 3.23
  Pod::Text: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-ReadmeFromPod
  homepage: http://metacpan.org/release/Dist-Zilla-Plugin-ReadmeFromPod
  license: http://dev.perl.org/licenses/
  repository: git://github.com/fayland/dist-zilla-plugin-readmefrompod.git
version: 0.21
x_authority: cpan:AVAR
